Repository TripInfoWeb/solitour-backend, pull requests merged in 2024-10, with the labels that each got.

#214 Fix : ci 이름 수정
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: refactor

#217 Fix(#216) : 유저, 일기 이미지 자동삭제 되지 않게 수정
  src/main/java/solitour_backend/solitour/diary/service/DiaryService.java
  src/main/java/solitour_backend/solitour/user_image/service/UserImageService.java
Labels: bug

#220 fix: 중복 코드 삭제
  build.gradle
Labels: bug

#223 Feat : 약관 동의시, 비동의시 유저 추가정보 입력
  src/main/java/solitour_backend/solitour/auth/controller/OauthController.java
  src/main/java/solitour_backend/solitour/auth/entity/Term.java
  src/main/java/solitour_backend/solitour/auth/entity/TermRepository.java
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/dto/request/AgreeUserInfoRequest.java
  src/main/java/solitour_backend/solitour/user/dto/request/DisagreeUserInfoRequest.java
  src/main/java/solitour_backend/solitour/user/entity/User.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepository.java
  src/main/java/solitour_backend/solitour/user/service/UserService.java
  src/main/java/solitour_backend/solitour/user/user_status/UserStatus.java
  src/main/resources/schema.sql
  src/main/resources/schema_test.sql
Labels: bug, feature

#224 Fix(#216) : 일기 이미지 하루 지나면 삭제되는 문제
  src/main/java/solitour_backend/solitour/diary/service/DiaryService.java
Labels: bug

#226 Fix/information pagenation filter sort
  src/main/java/solitour_backend/solitour/information/dto/response/InformationBriefResponse.java
  src/main/java/solitour_backend/solitour/information/repository/InformationRepositoryCustom.java
  src/main/java/solitour_backend/solitour/information/repository/InformationRepositoryImpl.java
  src/main/java/solitour_backend/solitour/information/service/InformationService.java
Labels: bug

#231 Release : 솔리투어 v1.0.1
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/solitour_backend/solitour/auth/controller/OauthController.java
  src/main/java/solitour_backend/solitour/auth/entity/Term.java
  src/main/java/solitour_backend/solitour/auth/entity/TermRepository.java
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/diary/service/DiaryService.java
  src/main/java/solitour_backend/solitour/information/controller/InformationController.java
  src/main/java/solitour_backend/solitour/information/dto/response/InformationBriefResponse.java
  src/main/java/solitour_backend/solitour/information/repository/InformationRepositoryCustom.java
  src/main/java/solitour_backend/solitour/information/repository/InformationRepositoryImpl.java
  src/main/java/solitour_backend/solitour/information/service/InformationService.java
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/dto/request/AgreeUserInfoRequest.java
  src/main/java/solitour_backend/solitour/user/dto/request/DisagreeUserInfoRequest.java
  src/main/java/solitour_backend/solitour/user/entity/User.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepository.java
  src/main/java/solitour_backend/solitour/user/service/UserService.java
  src/main/java/solitour_backend/solitour/user/user_status/UserStatus.java
  src/main/java/solitour_backend/solitour/user_image/service/UserImageService.java
  src/main/resources/docs/index.html
  src/main/resources/schema.sql
  src/main/resources/schema_test.sql
  src/test/java/solitour_backend/solitour/information/controller/InformationControllerTest.java
Labels: release

#237 Refactor : cors 설정 yml로 관리하도록 변경
  src/main/java/solitour_backend/solitour/auth/config/AuthConfiguration.java
  src/main/java/solitour_backend/solitour/auth/config/CorsProperties.java
Labels: refactor

#238 Feat(#228) : 정보 댓글 생성, 조회, 수정, 삭제
  src/main/java/solitour_backend/solitour/error/GlobalControllerAdvice.java
  src/main/java/solitour_backend/solitour/information/dto/response/InformationDetailResponse.java
  src/main/java/solitour_backend/solitour/information/entity/Information.java
  src/main/java/solitour_backend/solitour/information/repository/InformationRepository.java
  src/main/java/solitour_backend/solitour/information/service/InformationService.java
  src/main/java/solitour_backend/solitour/information_comment/controller/InformationCommentController.java
  src/main/java/solitour_backend/solitour/information_comment/dto/request/InformationCommentRequest.java
  src/main/java/solitour_backend/solitour/information_comment/dto/respose/InformationCommentListResponse.java
  src/main/java/solitour_backend/solitour/information_comment/dto/respose/InformationCommentResponse.java
  src/main/java/solitour_backend/solitour/information_comment/entity/InformationComment.java
  src/main/java/solitour_backend/solitour/information_comment/exception/CommentNotOwnerException.java
  src/main/java/solitour_backend/solitour/information_comment/exception/InformationCommentNotExistsException.java
  src/main/java/solitour_backend/solitour/information_comment/repository/InformationCommentRepository.java
  src/main/java/solitour_backend/solitour/information_comment/repository/InformationCommentRepositoryCustom.java
  src/main/java/solitour_backend/solitour/information_comment/repository/InformationCommentRepositoryImpl.java
  src/main/java/solitour_backend/solitour/information_comment/service/InformationCommentService.java
  src/main/resources/schema.sql
Labels: feature
