Repository TripInfoWeb/solitour-backend, pull requests merged in 2024-09, with the labels that each got.

#125 Feat(#121): 이미지 업로드 시 dev, prod 환경 구분+ 엔티티별로 구분해서 경로 설정
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/image/controller/ImageController.java
  src/main/java/solitour_backend/solitour/image/dto/response/ImageResponse.java
  src/main/java/solitour_backend/solitour/image/service/ImageService.java
Labels: feature, refactor

#126 Feat(#95) : 모임 북마크
  src/main/java/solitour_backend/solitour/book_mark_gathering/controller/BookMarkGatheringController.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/dto/response/BookMarkGatheringResponse.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/dto/response/BookMarkInfo.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/entity/BookMarkGathering.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/repository/BookMarkGatheringRepository.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/service/BookMarkGatheringService.java
  src/main/java/solitour_backend/solitour/gathering/repository/GatheringRepository.java
Labels: feature

#127 Feature(#121) : 이미지 엔티티 경로 분류 시에 enum사용하도록 변경
  src/main/java/solitour_backend/solitour/image/controller/ImageController.java
  src/main/java/solitour_backend/solitour/image/image_status/ImageType.java
Labels: feature, refactor

#129 Feat(#128) : 엑세스 토큰 만료시 401 코드 반환
  src/main/java/solitour_backend/solitour/auth/config/AuthInterceptor.java
Labels: feature, refactor

#137 Fix : 유저 정보글 조회, 유저 정보 북마크 조회 안되는 오류 수정
  src/main/java/solitour_backend/solitour/book_mark_gathering/controller/BookMarkGatheringController.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/service/BookMarkGatheringService.java
  src/main/java/solitour_backend/solitour/book_mark_information/controller/BookMarkInformationController.java
  src/main/java/solitour_backend/solitour/book_mark_information/service/BookMarkInformationService.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
Labels: bug

#143 Feat (#142): 모임 좋아요 기능 / 모임,정보 북마크, 좋아요 중복 체크 / 모임,정보 북마크,좋아요 예외, 상태 코드 처리
  src/main/java/solitour_backend/solitour/auth/config/AuthInterceptor.java
  src/main/java/solitour_backend/solitour/auth/config/TokenResolver.java
  src/main/java/solitour_backend/solitour/auth/exception/TokenNotExistsException.java
  src/main/java/solitour_backend/solitour/auth/exception/TokenNotValidException.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/controller/BookMarkGatheringController.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/exception/GatheringBookMarkNotExistsException.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/service/BookMarkGatheringService.java
  src/main/java/solitour_backend/solitour/book_mark_information/controller/BookMarkInformationController.java
  src/main/java/solitour_backend/solitour/book_mark_information/exception/InformationBookMarkNotExistsException.java
  src/main/java/solitour_backend/solitour/book_mark_information/service/BookMarkInformationService.java
  src/main/java/solitour_backend/solitour/error/GlobalControllerAdvice.java
  src/main/java/solitour_backend/solitour/great_gathering/controller/GreatGatheringController.java
  src/main/java/solitour_backend/solitour/great_gathering/entity/GreatGathering.java
  src/main/java/solitour_backend/solitour/great_gathering/exception/GatheringGreatNotExistsException.java
  src/main/java/solitour_backend/solitour/great_gathering/repository/GreatGatheringRepository.java
  src/main/java/solitour_backend/solitour/great_gathering/service/GreatGatheringService.java
  src/main/java/solitour_backend/solitour/great_information/controller/GreatInformationController.java
  src/main/java/solitour_backend/solitour/great_information/exception/InformationGreatNotExistsException.java
  src/main/java/solitour_backend/solitour/great_information/service/GreatInformationService.java
Labels: feature, refactor

#145 Fix(#144) : 내가 신청한 모임 조회시 내가 모집한 모임 제외하도록 수정
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
Labels: bug

#149 Fix(#148) : 태그 검색 인코딩 방식 변경
  src/main/java/solitour_backend/solitour/gathering/controller/GatheringController.java
  src/main/java/solitour_backend/solitour/information/controller/InformationController.java
Labels: bug

#151 Refactor(#150) : 회원 탈퇴 기능 향상
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/entity/User.java
  src/main/java/solitour_backend/solitour/user/service/UserService.java
  src/main/java/solitour_backend/solitour/user_image/entity/UserImage.java
Labels: feature, refactor

#163 Fix(#162) : qna 결과 얻을때 발생하는 no session 문제 해결
  src/main/java/solitour_backend/solitour/admin/controller/QnAController.java
  src/main/java/solitour_backend/solitour/admin/dto/response/QnaListResponseDto.java
  src/main/java/solitour_backend/solitour/admin/repository/QnARepository.java
  src/main/java/solitour_backend/solitour/admin/service/QnAService.java
Labels: bug

#168 Fix(#167) : 승인된 유저만 인원수에 포함하도록 쿼리 수정
  src/main/java/solitour_backend/solitour/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
Labels: bug

#170 Refactor(#169) : 일기 예외처리
  src/main/java/solitour_backend/solitour/diary/controller/DiaryController.java
  src/main/java/solitour_backend/solitour/diary/exception/DiaryNotExistsException.java
  src/main/java/solitour_backend/solitour/diary/repository/DiaryRepositoryImpl.java
  src/main/java/solitour_backend/solitour/diary/service/DiaryService.java
  src/main/java/solitour_backend/solitour/error/GlobalControllerAdvice.java
  src/main/java/solitour_backend/solitour/error/exception/ForbiddenAccessException.java
Labels: feature, refactor

#183 Fix : oauth 로그인 수정, 마이페이지 모임 오류 수정
  .gitignore
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/auth/service/TokenService.java
  src/main/java/solitour_backend/solitour/gathering/dto/response/GatheringMypageResponse.java
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryCustom.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
  src/main/java/solitour_backend/solitour/user/service/UserService.java
  src/main/resources/schema.sql
Labels: bug

#185 Fix: 모임 사용자 본명 대신 닉네임 전달
  src/main/java/solitour_backend/solitour/gathering/dto/response/GatheringBriefResponse.java
  src/main/java/solitour_backend/solitour/gathering/repository/GatheringRepositoryImpl.java
  src/main/resources/zone_category.sql
Labels: refactor

#186 Feat : 유저 블락 기능
  src/main/java/solitour_backend/solitour/auth/controller/OauthController.java
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/auth/service/dto/response/LoginResponse.java
  src/main/java/solitour_backend/solitour/error/GlobalControllerAdvice.java
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/exception/BlockedUserException.java
  src/main/java/solitour_backend/solitour/user/exception/DeletedUserException.java
  src/main/java/solitour_backend/solitour/user/exception/DormantUserException.java
  src/main/java/solitour_backend/solitour/user/user_status/UserStatus.java
Labels: feature

#187 Refactor : 로그인 로직 수정
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/dto/request/UpdateUserInfoRequest.java
  src/main/java/solitour_backend/solitour/user/entity/User.java
  src/main/java/solitour_backend/solitour/user/service/UserService.java
Labels: feature, refactor

#189 Refactor/gathering information
  src/main/java/solitour_backend/solitour/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/solitour_backend/solitour/information/dto/response/InformationBriefResponse.java
  src/main/java/solitour_backend/solitour/information/repository/InformationRepositoryImpl.java
Labels: refactor

#190 Feat : 유저 프로필 삭제 기능
  src/main/java/solitour_backend/solitour/auth/config/AuthInterceptor.java
  src/main/java/solitour_backend/solitour/auth/config/TokenResolver.java
  src/main/java/solitour_backend/solitour/auth/entity/Token.java
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/auth/support/kakao/KakaoConnector.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/controller/BookMarkGatheringController.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/entity/BookMarkGathering.java
  src/main/java/solitour_backend/solitour/book_mark_gathering/repository/BookMarkGatheringRepository.java
  src/main/java/solitour_backend/solitour/book_mark_information/controller/BookMarkInformationController.java
  src/main/java/solitour_backend/solitour/book_mark_information/service/BookMarkInformationService.java
  src/main/java/solitour_backend/solitour/diary/controller/DiaryController.java
  src/main/java/solitour_backend/solitour/diary/dto/response/DiaryDayContentDetail.java
  src/main/java/solitour_backend/solitour/diary/entity/Diary.java
  src/main/java/solitour_backend/solitour/diary/service/DiaryService.java
  src/main/java/solitour_backend/solitour/great_gathering/controller/GreatGatheringController.java
  src/main/java/solitour_backend/solitour/great_gathering/service/GreatGatheringService.java
  src/main/java/solitour_backend/solitour/great_information/controller/GreatInformationController.java
  src/main/java/solitour_backend/solitour/user/controller/UserController.java
  src/main/java/solitour_backend/solitour/user/entity/User.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryCustom.java
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
  src/main/java/solitour_backend/solitour/user/service/UserService.java
  src/main/java/solitour_backend/solitour/user_image/controller/UserImageController.java
  src/main/java/solitour_backend/solitour/user_image/service/UserImageService.java
Labels: feature, refactor

#191 Fix : 유저 프로필 이미지 url 경로 수정
  src/main/java/solitour_backend/solitour/user/service/UserService.java
Labels: bug

#192 docs: application-common 추가
  .github/workflows/deploy.yml
Labels: documentation

#193 Fix : 토큰 예외처리 수정
  src/main/java/solitour_backend/solitour/gathering/controller/GatheringController.java
  src/main/java/solitour_backend/solitour/information/controller/InformationController.java
Labels: bug

#194 Refactor : 일기 장소 글자수 수정
  src/main/java/solitour_backend/solitour/diary/service/DiaryService.java
  src/main/resources/schema.sql
Labels: refactor

#195 Fix : 비활성화 상태에서도 로그인 되도록 수정
  src/main/java/solitour_backend/solitour/user/repository/UserRepository.java
Labels: bug

#197 fix: 좋아요 수 구하는 절 수정
  src/main/java/solitour_backend/solitour/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/solitour_backend/solitour/information/repository/InformationRepositoryImpl.java
Labels: bug

#198 fix : 로그인 유저 상태 확인 수정
  src/main/java/solitour_backend/solitour/user/repository/UserRepository.java
Labels: bug

#202 Fix : 정보 카테고리 이름 추가
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
Labels: bug

#203 Fix : 카테고리 이름 필드 추가
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
Labels: bug

#204 Refactor : 성별입력시 유저 프로필 변경
  src/main/java/solitour_backend/solitour/user/service/UserService.java
Labels: refactor

#205 Fix : 유저 프로필이 디폴트 프로필일때만 변경
  src/main/java/solitour_backend/solitour/user/service/UserService.java
Labels: refactor

#206 fix: applicatns 부분 join -> 서브쿼리로 수정
  src/main/java/solitour_backend/solitour/gathering/repository/GatheringRepositoryImpl.java
Labels: bug

#207 Fix : 마이페이지 모임 조회 오류 수정
  src/main/java/solitour_backend/solitour/user/repository/UserRepositoryImpl.java
Labels: bug

#209 Fix : main ci시 무한로딩 되는 문제
  .github/workflows/deploy.yml
  gradlew
  src/main/resources/category.sql
  src/main/resources/gathering_category.sql
  src/main/resources/schema.sql
  src/main/resources/schema_test.sql
  src/main/resources/zone_category.sql
Labels: bug

#210 Fix : 카카오 회원탈퇴 오류 수정 , 카카오 추가정보 있을때 회원가입
  src/main/java/solitour_backend/solitour/auth/controller/OauthController.java
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/auth/service/TokenService.java
  src/main/java/solitour_backend/solitour/auth/support/kakao/dto/request/CreateUserInfoRequest.java
Labels: bug

#211 Feat : 네이버 oauth 기능
  src/main/java/solitour_backend/solitour/auth/controller/OauthController.java
  src/main/java/solitour_backend/solitour/auth/exception/RevokeFailException.java
  src/main/java/solitour_backend/solitour/auth/exception/UnsupportedLoginTypeException.java
  src/main/java/solitour_backend/solitour/auth/exception/UserRevokeErrorException.java
  src/main/java/solitour_backend/solitour/auth/service/OauthService.java
  src/main/java/solitour_backend/solitour/auth/support/naver/NaverConnector.java
  src/main/java/solitour_backend/solitour/auth/support/naver/NaverProvider.java
  src/main/java/solitour_backend/solitour/auth/support/naver/dto/NaverTokenAndUserResponse.java
  src/main/java/solitour_backend/solitour/auth/support/naver/dto/NaverTokenResponse.java
  src/main/java/solitour_backend/solitour/auth/support/naver/dto/NaverUserResponse.java
  src/main/java/solitour_backend/solitour/error/GlobalControllerAdvice.java
Labels: feature

#212 Refactor : 테스트 ci , 배포 ci 분리
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: refactor
